############################################
# Installing ansi-60-keyboard combinations #
############################################

install:
	mkdir -p ~/.config/autokey/data/
	cp -rfv ansi-60-keyboard ~/.config/autokey/data/
	autokey &
	
uninstall:
	rm -rfv ~/.config/autokey/data/
	autokey &

